# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Mail
version:      0.11
version_from: lib/HTML/Mail.pm
installdirs:  site
requires:
    HTML::Parser:                  3
    LWP::UserAgent:                2
    MIME::Lite:                    1
    URI:                           1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
